### ISSUE TITLE
Exclude current playlist from song action button

### ISSUE THREAD

**Issue by fcrespel** [fcrespel/karaplan#27]
For songs displayed in a playlist, remove the current playlist for the song action button (and counter)

**Comment by sdenef** [comment]
Hello,
Are you sure? :)
It sounds good for me as is. I tried on Spotify and Amazon Music. UI is not exactly the same, but when you select a song in a playlist then you can select _Add to a playlist_ and it displays all playlists (including current one) + _Create a new playlist_ option.

**Comment by fcrespel** [comment]
Hello @sdenef and thanks for the contribution.
You're right I'm no longer sure about this one 😅... it may be unexpected to _not_ see the current playlist in the list. Instead, we could perhaps highlight it specifically in the dropdown? (e.g. different color or "current" badge next to it)
